[workspace]
resolver = "2"
members = ["crates/tenv-cli", "crates/tenv-core"]

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/Joshua-OA/terms-env"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
tenv-core = { path = "crates/tenv-core" }
